# 配置Redis连接池的连接信息
spring:
  data:
    redis:
      host: 192.168.238.130 # Linux虚拟机ip地址
      port: 6379 # Redis的端口号
      password: JMGMKSZ1919810
      lettuce: # 注意：spring默认使用lettuce进行Redis的操作！
        pool:
          max-active: 8 # 最大连接数
          max-idle: 8 # 最大空闲连接数
          min-idle: 0 # 最小空闲连接数
          max-wait: 200 # 最长等待时间(ms)
